//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataVerse
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string email { get; set; }
        public int id { get; set; }
    
        public virtual Phone Phone { get; set; }
    }
}
